version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  debug:
    class: logging.FileHandler
    leve: DEBUG
    formatter: simple
    file: info.log
loggers:
  debug:
    level: DEBUG
    qualname: DEBUG
    handlers: debugs
  error:
    level: ERROR
    qualname: INFO
    handlers: errors
  info:
    level: INFO
    qualname: INFO
    handlers: infos
root:
  level: DEBUG,INFO,ERROR
  handlers: [console]

## https://docs.python.org/zh-cn/3/library/logging.config.html#logging-config-api